apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.samplecontroller.lj.io
spec:
  group: samplecontroller.lj.io
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
